### ISSUE TITLE
Allow manually overriding the standard shaders with the compat shaders

### ISSUE THREAD

**Issue by Sponk** [Sponk/NeoEditor#117]
This will allow more control over the performance.

**Comment by ypflanzer** [comment]
Update: The new renderer has some GL3.3 shaders which pull in some extensions if they are available. The original standard renderer is now called "MobileRenderer" since it's proven to work on GLES systems.

**Comment by ypflanzer** [comment]
This issue is not applicable anymore since shaders are not hard-coded in the renderer but loaded from files in the game asset directory. Switching or editing those files gives full control over rendering thus solving this issue.
