### ISSUE TITLE
Can't save Prefab

### ISSUE THREAD

**Issue by jamesgeek** [Sponk/NeoEditor#148]
Every time I try to save a Prefab, it does not save! It does not matter what I try to save, it does not work in every case.

Unfortunately I get no error message or something similar, so I'm not sure what could be causing this?

The load of old Prefabs, however, works without any problems.

**Comment by Sponk** [comment]
Could you please send me the project you tried it with?

**Comment by jamesgeek** [comment]
Here it is:
https://copy.com/vJ6Tvau1qorHtNwp

I have just created a new project with a simple box-mesh and a camera.
The box-mesh can not be saved as a prefab.

**Comment by jamesgeek** [comment]
If it helps, here you can find the complete log of neo-editor:
https://copy.com/aZJmfU8F8kmGGvbB

There are also some critical errors. I have no idea if these have to do with this problem.

**Comment by Sponk** [comment]
I fixed it. I made a mistake when converting the Lua API to be language independent. That messed up some argument calculations.

Retest :D

**Comment by jamesgeek** [comment]
Thank you Sponk!

I have tried a few cases and could now save each mesh combination as a Prefab. Only pre-existing groups can not be saved as a Prefab, but this is probably more a Feature-Request. ;-)

**Comment by Sponk** [comment]
Nice to hear that it is fixed :D
