### ISSUE TITLE
NeoEditor crashes when adding a camera or light source

### ISSUE THREAD

**Issue by Murii** [Sponk/NeoEditor#153]
Hello,as the title says the engine crashes everytime when I want to add a camera.And then this is what i get:
![image](https://cloud.githubusercontent.com/assets/7363306/5695036/9b83477c-9993-11e4-95f1-df83a2bde65a.png)

**Comment by Sponk** [comment]
Hey Murii!

It looks as if you are using the master branch. Please update to the development version and try again, it is very likely that the issue you encounter is already fixed.

Please send me the logfile if that does not help. You can find it in "%APPDATA%\neo-editor" if I'm not mistaken.

Thank you for reporting!

**Comment by Murii** [comment]
Where can i download the dev version?

**Comment by Sponk** [comment]
If you downloaded the code via zip you can download the dev code here: https://github.com/Sponk/NeoEditor/tree/development

If you used git, simply do "git checkout development".

**Comment by Murii** [comment]
Thanks for you answer!

**Comment by Sponk** [comment]
No problem :D

**Comment by Murii** [comment]
Ok so I started the engine and this is what i get.
![image](https://cloud.githubusercontent.com/assets/7363306/5695139/66d85c90-999a-11e4-83b7-a8e2e15a9298.png)

**Comment by Sponk** [comment]
I know your problem

VS likes to put some build description after the build directory, messing up the build system.
Try to copy the content of "<build>/BinaryOutput" to "<build>/BinaryOutput/Debug"

**Comment by Murii** [comment]
Like this ? 
![image](https://cloud.githubusercontent.com/assets/7363306/5695177/5061f9f0-999d-11e4-9351-4a8b11837300.png)

**Comment by Sponk** [comment]
You should have a directory named "gui" in your BinaryOutput directory. Copy this to the executable you built with VS so the editor can find it. You get this crash because the editor wants to load icons and meshes to display the light. 
There should be an error message included preventing the application from simply dying if that happens in the future. And the VS build needs to be fixed as well, there should not be this "Debug" prefix.

**Comment by Murii** [comment]
The only thing I have in BinaryOutput is a folder named Debug 
![image](https://cloud.githubusercontent.com/assets/7363306/5695197/3d580dda-999e-11e4-9704-b1d7ee03c252.png)
And the only folder named ,,gui,, is here : 
![image](https://cloud.githubusercontent.com/assets/7363306/5695200/5025d42e-999e-11e4-933f-2d9e99a84607.png)
I copied the folder into the Debug folder but it still crashes :(

**Comment by Murii** [comment]
OK,I made the camera to work! I donwloaded the engine and copied to gui and fonts into debug folder!

**Comment by Murii** [comment]
But now when i want to open a project i get this :)) 

![image](https://cloud.githubusercontent.com/assets/7363306/5695229/2912de12-999f-11e4-9c17-fc4218851fad.png)

**Comment by Murii** [comment]
I dont know what happened but I pressed Retry then more stuff happened and I end up here:
![image](https://cloud.githubusercontent.com/assets/7363306/5695232/77c7858a-999f-11e4-8906-f622ecd89acd.png)
After that I could open a project.Wierd

**Comment by Murii** [comment]
After commenting the for loop everything works just fine!

**Comment by Sponk** [comment]
Which for loop?

**Comment by Murii** [comment]
from 825

**Comment by Murii** [comment]
So?Where can i find .exe file to start the game?

**Comment by Sponk** [comment]
Everything should be in the BinaryOutput directory somewhere

Simply use the "Update Player" menu in the editor to copy the player and all needed libs to your project.

Or you can export a finished version by using the "Publish" menu.

**Comment by Murii** [comment]
I pressed the Publish button and it made a new folder and there I have this:
![image](https://cloud.githubusercontent.com/assets/7363306/5695345/00e8c332-99a6-11e4-9029-71ad557683fb.png)

**Comment by Sponk** [comment]
Did you build the whole project or just the editor?

**Comment by Murii** [comment]
I loded a project from SmallDemos folder (downloaded from maratis`s site) and then I pressed the publish button and the result us up there in the pic

**Comment by Sponk** [comment]
No, I meant in VS. You need to build every project for the editor to be able to copy everything necessary. Just build the whole workspace.

**Comment by Murii** [comment]
Oh,i see.Sorry I did not do that!

**Comment by Sponk** [comment]
Btw: We can communicate much faster using IRC chat: http://www.neo-engine.de/irc-contact/

**Comment by Murii** [comment]
Sure!

**Comment by Murii** [comment]
I used IRC chat but I cant see my own message or anyone else.So I`m going ask here.Where can I see a simple usage of the new 2D api?Can i download a project?

**Comment by Sponk** [comment]
There is plenty of documentation about it available: http://neo-engine.de/documentation/LuaDoc/
The color scheme still needs some work...

**Comment by Sponk** [comment]
If you want another channel for communication you can join our forum: http://www.neo-engine.de/forums/
