### ISSUE TITLE
Cant see any 2D sprites!

### ISSUE THREAD

**Issue by Murii** [Sponk/NeoEditor#167]
For the past 3h I tried to see my sprites but I cant! I took the camera and rotate it,translate and all that stuff but I cant see any sprites!Also I dont get any errors just blank space!

**Comment by Murii** [comment]
This day was totaly unproductive...

**Comment by Sponk** [comment]
How did you try to render them?

**Comment by Murii** [comment]
as usual using :

dofile("SDK/Graphics2D.lua")
sprite = Sprite(120,130,32,32,"maps/white.png")
mainCanvas:addWidget(sprite)

**Comment by Sponk** [comment]
What does the logfile/console say?

**Comment by Murii** [comment]
it gives no error.

**Comment by Murii** [comment]
Right now I`m trying to compile the latest dev version from github.

**Comment by Sponk** [comment]
Ok. You might want to join the IRC chat. It might be easier to help you there.
It's in #neo3d on irc.freenode.net

**Comment by Murii** [comment]
I`m in thx!
