### ISSUE TITLE
Cant code inside C++ and export functions to Lua

### ISSUE THREAD

**Issue by Murii** [Sponk/NeoEditor#169]
![image](https://cloud.githubusercontent.com/assets/7363306/5793369/edd9a74e-9f49-11e4-9580-fe4c70f6e7a3.png)
![image](https://cloud.githubusercontent.com/assets/7363306/5793376/024dec6c-9f4a-11e4-81e1-aa6bb2444428.png)
![image](https://cloud.githubusercontent.com/assets/7363306/5793381/12bb36a4-9f4a-11e4-8b62-394cb3069bcd.png)
![image](https://cloud.githubusercontent.com/assets/7363306/5793384/303eb368-9f4a-11e4-8d7c-c712b99dc0b1.png)
![image](https://cloud.githubusercontent.com/assets/7363306/5793401/0be2b9be-9f4b-11e4-9e8d-504a7cf7808b.png)
![image](https://cloud.githubusercontent.com/assets/7363306/5793408/4da0f50a-9f4b-11e4-85ce-070fe6b8d0f3.png)

**Comment by Sponk** [comment]
I made some changes to the testing API and added a stub for those functions for you. They work and you just have to fill in your code.

Don't forget to git pull && recompile :D

**Comment by Murii** [comment]
Okay ill have a look later this day.thanks

Trimis de pe iPhone-ul meu

Pe 19.01.2015, la 00:25, Yannick Pflanzer <notifications@github.com> a scris:

**Comment by Murii** [comment]
I have literally no explanation why now the setVisible is working.None! :))
