### ISSUE TITLE
Delta Time is not used in 2D

### ISSUE THREAD

**Issue by Murii** [Sponk/NeoEditor#198]
I`ve tried to use the value 500 and then 20 for making an 2D sprite move on X axe but it made him go so fast that I barely saw it.Clearly this shouldn't happen.Just to be sure I tested the exact same code in Libgdx this time *deltaTime and it moved fast but not like in neo.Also I looked into Neo`s source code and I could not see anything related to delta time.

**Comment by Sponk** [comment]
I just merged your patch. Closing.
