### ISSUE TITLE
Feature-Request: loadTextFile(_filename)

### ISSUE THREAD

**Issue by cherub84** [Sponk/NeoEditor#200]
Hi Sponk! :D

Currently I am working on a slightly larger game with the "Neo Engine" and use external files for the runtime load and save. The standard LUA functionality (e.g. io.open) unfortunately only works before the actual baking of the NPK file.

In this case, it is currently impossible to hide all the external files (e.g. dialogue-files) from the player.

A loadTextFile(_filename) function could help, because you simply could access a file in the NPK file similar to the loadMesh(meshfile) function.

**Comment by Sponk** [comment]
Hey cherub84!
First of all: Welcome!

There actually exists a "loadTextFile" function in the C++ code but it is not exposed to the script API.
It should be trivial to do so.

I will create the binding for it right away.

**Comment by Sponk** [comment]
Ok, It is implemented now and pushed to the development branch.
I did not test it but it should work.

**Comment by cherub84** [comment]
It works! :D Thank you Sponk!

**Comment by Sponk** [comment]
Good to hear :)
