### ISSUE TITLE
getDelta does not work when publishing projects

### ISSUE THREAD

**Issue by Sponk** [Sponk/NeoEditor#205]

**Comment by Murii** [comment]
What error do you get?

**Comment by Sponk** [comment]
It just says "Trying to call a nil value" or the like. I will look over it.

**Comment by Murii** [comment]
Weird because it works inside the editor.

**Comment by Sponk** [comment]
I know. Where did you implement the function? It isn't in ScriptApi.cpp in NeoCommon.

**Comment by Murii** [comment]
The function is implemented inside main.cpp and is called there too.

**Comment by Sponk** [comment]
Then I know the problem. The editor does not use the same main file as the player.

**Comment by Sponk** [comment]
Fixed.
