### ISSUE TITLE
There are two classes which do the same: "NeoGame.cpp" and "Game.cpp"

### ISSUE THREAD

**Issue by Murii** [Sponk/NeoEditor#222]
Both of them look the same,so why bother having two?

**Comment by Sponk** [comment]
Game.cpp includes profiling for the editor implementation of the class, NeoGame does not.

**Comment by Sponk** [comment]
https://github.com/Sponk/NeoEditor/blob/development/Neo/NeoEditor/Game/Game.cpp vs. https://github.com/Sponk/NeoEditor/blob/development/SDK/NeoEngine/Sources/NeoGame.cpp
