### ISSUE TITLE
NeoLua error!

### ISSUE THREAD

**Issue by Murii** [Sponk/NeoEditor#223]
[ Warn ] You try to load a level that was created using Maratis. in M_loadLevel
[ Warn ] Will try to convert from old level version '3.1'. in M_loadLevel
[ Error ] Lua Script: 
[string "require("NeoLua")..."]:3: attempt to index global 'NeoLua' (a nil value)
 in runString
[ Error ] Stacktrace:

	[0] [C]:-1 -- dofile[C]
	[1] [string "..."]:7 -- <unknown> [main]

 in printStack
[ Error ] Could not execute NativeSDKTest.lua in doFile
The program has unexpectedly finished.

This is what I get when I'm doing: Project -> Update player.The same result I get if I'm trying to run the sample from sublime text 3. Also after doing Project -> Update player Neo wont let me start the engine again until I delete "libassimp.so.3.1.1" and recompile.

**Comment by Sponk** [comment]
Keep in mind to start your application with the project directory as the working directory or else it can't find NeoLua.dll/NeoLua.so.
You might also want to check if the file even exists.

**Comment by Murii** [comment]
![screenshot from 2015-06-30 12 57 49](https://cloud.githubusercontent.com/assets/7363306/8428515/c2a3f6d4-1f27-11e5-9700-93efdb6761ed.png)
![screenshot from 2015-06-30 12 58 21](https://cloud.githubusercontent.com/assets/7363306/8428520/ca6938b6-1f27-11e5-8e07-4b8a04ca79ef.png)
Like this?

**Comment by Sponk** [comment]
You are missing the NeoLua.so file.
Try "sudo apt-get install swig" and rebuild. This should fix your issue.
The plug-in is only built if the source files could be updated and swig is needed for that.

**Comment by Murii** [comment]
I've installed what you gave me and still no NeoLua.so.

**Comment by Sponk** [comment]
Did you re-run cmake? It only searches for swig once and caches the result.
Try to delete the CMakeCache.txt file and re-run cmake.

**Comment by Murii** [comment]
Yep: 
[ Warn ] You try to load a project that was created using Maratis. in loadXML
[ Warn ] You try to load a level that was created using Maratis. in M_loadLevel
[ Warn ] Will try to convert from old level version '3.1'. in M_loadLevel
The program has unexpectedly finished.
/home/omx/Dev/NeoEditor-build/BinaryOutput/NeoEditor crashed

**Comment by Sponk** [comment]
It is time to use gdb! :D
