### ISSUE TITLE
Shaders are incorrectly deleted.

### ISSUE THREAD

**Issue by ghost** [Sponk/NeoEditor#246]
The method form here is not correct: https://github.com/Sponk/NeoEditor/blob/development/Neo/Common/Contexts/GL4Context.cpp#L693

glDetachShader(program, vertex);
glDetachShader(program, fragment);

This must be done since deleting a shader doesn't automatically detach it from the program (as described here: http://docs.gl/gl3/glDetachShader).

**Comment by ypflanzer** [comment]
Thanks for pointing that out. I wasn't familiar with that, I thought destroying the shader would automatically detach it as well.
