### ISSUE TITLE
Debug feature problems when compiling for AMD64 on Windows

### ISSUE THREAD

**Issue by Akira1San** [Sponk/NeoEditor#249]
This time ive managed to install the Dx sdk. compiling with VS 2013 update 5, on Win 8.1 64b
Cmake - http://www.pasteall.org/63630
Error list - http://www.pasteall.org/63631
Output - http://www.pasteall.org/63632

**Comment by ypflanzer** [comment]
47>------ Build started: Project: INSTALL, Configuration: Release x64 ------
47>  -- Install configuration: "Release"
47>  CMake Error at cmake_install.cmake:31 (file):
47>    file cannot create directory: C:/Program Files/NEO/Neo.  Maybe need
47>    administrative privileges.

You try to install to a location that can not be written without admin rights. Try starting VS as admin and rebuild. Alternatively you can build the "PACKAGE" target and install the generated setup file.

**Comment by Akira1San** [comment]
Solved!
Now you could add to the windows compile doc:
You need to install DirectX SDK and NSIS, you need to be an admin to compile.

**Comment by ypflanzer** [comment]
No, you don't need to be an admin to compile. Only for installation you need to be.
Also: The 64bit build is broken and needs to be fixed.

**Comment by ypflanzer** [comment]
It was fixed some commits ago, closing.
