### ISSUE TITLE
Emscripten Javascript Port

### ISSUE THREAD

**Issue by BitPuffin** [Sponk/NeoEditor#49]
Would be very useful to enable Neo games to run in a web browser, as well as on Firefox OS.

**Comment by ypflanzer** [comment]
It compiles and runs, the new GLESRenderer works perfectly fine. It uses the same NPKs as the other platforms. Missing are:
- Bullet physics support
- Lua API support (Lua itself is supported)
- OpenAL support

Those are mostly porting existing plugins to Emscripten.

**Comment by ypflanzer** [comment]
Finally everything is in place and 3D rendering is working as well.
Now it's just a case of finding bugs and fixing them.
